gscam_node:
  ros__parameters:
    camera_resolution: [1280, 720]
    frame_rate: 30
    image_resolution: [224, 224]
    rotate: 180
    format: "BGRx"

joy_node:
  ros__parameters:
    dev: "/dev/input/js0"

# joystick_controller_node:
#   ros__parameters:
#     # Joystick Ratio Settings
#     throttle_ratio: 0.6
#     steer_ratio: -1.0
#     # Joystick Channel Setting
#     throttle_axis: 4
#     steer_axis: 0

joystick_controller_node:
  ros__parameters:
    throttle_ratio: 0.6
    steer_ratio: -1.0

    steer_axis: 0

    decel_button: 0
    stop_button: 1
    init_speed_button: 2
    accel_button: 3

    initial_speed: 0.20
    speed_step: 0.02
    min_speed: 0.0
    max_speed: 0.40

pca9685_actuator_node:
  ros__parameters:
    # PWM Frequency and Bus Configuration
    bus_device: "/dev/i2c-7"
    pwm_frequency: 60

    # Throttle Configuration
    throttle_pwm_channel: 0
    throttle_min_pulsewidth: 1000
    throttle_max_pulsewidth: 2000
    throttle_mid_pulsewidth: 1500

    # Steer Configuration
    steer_pwm_channel: 1
    steer_min_pulsewidth: 1200
    steer_max_pulsewidth: 2000
    steer_mid_pulsewidth: 1600


